language: ruby
rvm:
  - 2.2.3
before_install: gem install bundler -v 1.10.6
language: ruby
cache: bundler

rvm:
  - jruby
  - 2.0.0

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - my@email.com
    on_failure: change
    on_success: never
